news_rails_url: https://news.railstutorial.org/
rails_toturial_url: https://www.railstutorial.org/
rails_toturial_author: https://www.michaelhartl.com/
contact_url: https://www.railstutorial.org/contact
book_url: https://www.railstutorial.org/book
help_url: https://www.railstutorial.org/help
rails_page: https://rubyonrails.org/
