app_url: 127.0.0.1
app_port: 3000
valid_email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
max_length_name: 20
min_length_email: 20
max_length_email: 255
min_length_password: 6
news_rails_url: https://news.railstutorial.org/
rails_toturial_url: https://www.railstutorial.org/
rails_toturial_author: https://www.michaelhartl.com/
contact_url: https://www.railstutorial.org/contact
book_url: https://www.railstutorial.org/book
help_url: https://www.railstutorial.org/help
rails_page: https://rubyonrails.org/
gravatar_url: https://secure.gravatar.com/avatar/
gravatar_change_url: https://gravatar.com/emails
gravar_user_size_80: 80
gravar_user_size_50: 50
email_expired_hour_2: 2
